title: Logoto
email: briffraff6@gmail.com
description: It is a site for logo design!
baseurl: "/logoto"
url: ""

global:
  nickname: riffraff
  github_username: briffraff

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-coffeescript

#sass:
#  style: compressed
#  sass_dir: _sass

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
