title: Logoto
email: briffraff6@gmail.com
description: It is a site for logo design!
baseurl: "/logoto"
url: ""
#destination: docs
global:
  nickname: riffraff
  github_username: briffraff

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-coffeescript

collections:
  teams:
    output: true

collections_dir: collections

game: "/assets/images/kosh.jpeg"

#  https://tableconvert.com/?output=json
#  https://jsonformatter.curiousconcept.com/

#sass:
#  style: compressed
#  sass_dir: _sass

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
